### ISSUE TITLE
system HUD appears with the VolumeBar

### ISSUE THREAD

**Issue by piemonte** [gizmosachin/VolumeBar#5]
Hey @gizmosachin ! Amazing library.

If I get the opportunity to determine what's causing this bug, I'll look into but wanted to report it just incase. I've setup the volume bar like so, but the system HUD still appears when pushing the iPhone's physical volume buttons.
  
```swift 
  // MARK: - UIApplicationDelegate
    
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        
        // setup volume bar
        do {
            try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryAmbient)
            let volumeBar = VolumeBar.sharedInstance
            volumeBar.animationStyle = .slide
            volumeBar.barHeight = 5
            volumeBar.segmentCount = 16
            volumeBar.interitemSpacing = 0
            volumeBar.statusBarHidden = true
            volumeBar.start()
        } catch {
            print("failed to configure audio session")
        }

 //...
```

**Comment by gizmosachin** [comment]
Thanks @piemonte! I tested that code and initially wasn't seeing the system HUD, but after backgrounding the app and re-opening it, the system HUD reappeared and the VolumeBar didn't (fixed in d21186c3a022d1b1b2feab5544b79e281eb445c5). 

Just pushed v2.0.1 - can you see if that fixes it?

**Comment by piemonte** [comment]
@gizmosachin hey, ofcourse. so i installed 2.0.2 and unfortunately am still seeing the same behavior.

**Comment by gizmosachin** [comment]
@piemonte 😕  I'll look into it some more over the next few days.

**Comment by gizmosachin** [comment]
@piemonte I tweaked it so that the `MPVolumeView` is a subview of the `volumeWindow` (instead of the app's first window) and changed the behavior so that `volumeWindow.hidden = false` in between calls to `start` and `stop`.

Hopefully this prevents the system HUD from appearing - could you see if that fixes it?

**Comment by piemonte** [comment]
@gizmosachin thanks so much! works well. 👍

**Comment by gizmosachin** [comment]
@piemonte 🙌🏽
